config/routes.rb
Rails.application.routes.draw do
  
  resources :mahasiswas
  resources :mata_kuliahs
  resources :proyek_pendidikans
  resources :program_studis
  resources :kelas
  resources :dosens
  get 'welcome/index'
  root to: 'homes#index'
  devise_for :users,
  
  controllers: { sessions: 'users/sessions' }   
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :homes
  

end

app/models/program_studi.rb
class ProgramStudi < ApplicationRecord
end

app/controllers/program_studis_controller.rb
class ProgramStudisController < ApplicationController
  before_action :set_program_studi, only: [:show, :edit, :update, :destroy]

  # GET /program_studis
  # GET /program_studis.json
  def index
    @program_studis = ProgramStudi.all
  end

  # GET /program_studis/1
  # GET /program_studis/1.json
  def show
  end

  # GET /program_studis/new
  def new
    @program_studi = ProgramStudi.new
  end

  # GET /program_studis/1/edit
  def edit
  end

  # POST /program_studis
  # POST /program_studis.json
  def create
    @program_studi = ProgramStudi.new(program_studi_params)

    respond_to do |format|
      if @program_studi.save
        format.html { redirect_to @program_studi, notice: 'Program studi was successfully created.' }
        format.json { render :show, status: :created, location: @program_studi }
      else
        format.html { render :new }
        format.json { render json: @program_studi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /program_studis/1
  # PATCH/PUT /program_studis/1.json
  def update
    respond_to do |format|
      if @program_studi.update(program_studi_params)
        format.html { redirect_to @program_studi, notice: 'Program studi was successfully updated.' }
        format.json { render :show, status: :ok, location: @program_studi }
      else
        format.html { render :edit }
        format.json { render json: @program_studi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /program_studis/1
  # DELETE /program_studis/1.json
  def destroy
    @program_studi.destroy
    respond_to do |format|
      format.html { redirect_to program_studis_url, notice: 'Program studi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program_studi
      @program_studi = ProgramStudi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_studi_params
      params.require(:program_studi).permit(:kode_ps, :nama_program_studi)
    end
end

app/helpers/program_studis_helper.rb
module ProgramStudisHelper
end

app/views/program_studis/_form.html.erb
<%= form_with(model: program_studi, local: true) do |form| %>
  <% if program_studi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program_studi.errors.count, "error") %> prohibited this program_studi from being saved:</h2>

      <ul>
      <% program_studi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kode_ps %>
    <%= form.text_field :kode_ps %>
  </div>

  <div class="field">
    <%= form.label :nama_program_studi %>
    <%= form.text_field :nama_program_studi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/program_studis/edit.html.erb
<h1>Editing Program Studi</h1>

<%= render 'form', program_studi: @program_studi %>

<%= link_to 'Show', @program_studi %> |
<%= link_to 'Back', program_studis_path %>

app/views/program_studis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Program Studis</h1>

<table>
  <thead>
    <tr>
      <th>Kode ps</th>
      <th>Nama program studi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @program_studis.each do |program_studi| %>
      <tr>
        <td><%= program_studi.kode_ps %></td>
        <td><%= program_studi.nama_program_studi %></td>
        <td><%= link_to 'Show', program_studi %></td>
        <td><%= link_to 'Edit', edit_program_studi_path(program_studi) %></td>
        <td><%= link_to 'Destroy', program_studi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program Studi', new_program_studi_path %>

app/views/program_studis/new.html.erb
<h1>New Program Studi</h1>

<%= render 'form', program_studi: @program_studi %>

<%= link_to 'Back', program_studis_path %>

app/views/program_studis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kode ps:</strong>
  <%= @program_studi.kode_ps %>
</p>

<p>
  <strong>Nama program studi:</strong>
  <%= @program_studi.nama_program_studi %>
</p>

<%= link_to 'Edit', edit_program_studi_path(@program_studi) %> |
<%= link_to 'Back', program_studis_path %>