config/routes.rb
Rails.application.routes.draw do
  
  resources :mahasiswas
  resources :mata_kuliahs
  resources :proyek_pendidikans
  resources :program_studis
  resources :kelas
  resources :dosens
  get 'welcome/index'
  root to: 'homes#index'
  devise_for :users,
  
  controllers: { sessions: 'users/sessions' }   
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :homes
  

end

app/models/proyek_pendidikan.rb
class ProyekPendidikan < ApplicationRecord
end

app/controllers/proyek_pendidikans_controller.rb
class ProyekPendidikansController < ApplicationController
  before_action :set_proyek_pendidikan, only: [:show, :edit, :update, :destroy]

  # GET /proyek_pendidikans
  # GET /proyek_pendidikans.json
  def index
    @proyek_pendidikans = ProyekPendidikan.all
  end

  # GET /proyek_pendidikans/1
  # GET /proyek_pendidikans/1.json
  def show
  end

  # GET /proyek_pendidikans/new
  def new
    @proyek_pendidikan = ProyekPendidikan.new
  end

  # GET /proyek_pendidikans/1/edit
  def edit
  end

  # POST /proyek_pendidikans
  # POST /proyek_pendidikans.json
  def create
    @proyek_pendidikan = ProyekPendidikan.new(proyek_pendidikan_params)

    respond_to do |format|
      if @proyek_pendidikan.save
        format.html { redirect_to @proyek_pendidikan, notice: 'Proyek pendidikan was successfully created.' }
        format.json { render :show, status: :created, location: @proyek_pendidikan }
      else
        format.html { render :new }
        format.json { render json: @proyek_pendidikan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyek_pendidikans/1
  # PATCH/PUT /proyek_pendidikans/1.json
  def update
    respond_to do |format|
      if @proyek_pendidikan.update(proyek_pendidikan_params)
        format.html { redirect_to @proyek_pendidikan, notice: 'Proyek pendidikan was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyek_pendidikan }
      else
        format.html { render :edit }
        format.json { render json: @proyek_pendidikan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyek_pendidikans/1
  # DELETE /proyek_pendidikans/1.json
  def destroy
    @proyek_pendidikan.destroy
    respond_to do |format|
      format.html { redirect_to proyek_pendidikans_url, notice: 'Proyek pendidikan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyek_pendidikan
      @proyek_pendidikan = ProyekPendidikan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyek_pendidikan_params
      params.require(:proyek_pendidikan).permit(:kode_pp, :proyek_pendidikan)
    end
end

app/helpers/proyek_pendidikans_helper.rb
module ProyekPendidikansHelper
end

app/views/proyek_pendidikans/_form.html.erb
<%= form_with(model: proyek_pendidikan, local: true) do |form| %>
  <% if proyek_pendidikan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyek_pendidikan.errors.count, "error") %> prohibited this proyek_pendidikan from being saved:</h2>

      <ul>
      <% proyek_pendidikan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kode_pp %>
    <%= form.text_field :kode_pp %>
  </div>

  <div class="field">
    <%= form.label :proyek_pendidikan %>
    <%= form.text_field :proyek_pendidikan %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyek_pendidikans/edit.html.erb
<h1>Editing Proyek Pendidikan</h1>

<%= render 'form', proyek_pendidikan: @proyek_pendidikan %>

<%= link_to 'Show', @proyek_pendidikan %> |
<%= link_to 'Back', proyek_pendidikans_path %>

app/views/proyek_pendidikans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyek Pendidikans</h1>

<table>
  <thead>
    <tr>
      <th>Kode pp</th>
      <th>Proyek pendidikan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyek_pendidikans.each do |proyek_pendidikan| %>
      <tr>
        <td><%= proyek_pendidikan.kode_pp %></td>
        <td><%= proyek_pendidikan.proyek_pendidikan %></td>
        <td><%= link_to 'Show', proyek_pendidikan %></td>
        <td><%= link_to 'Edit', edit_proyek_pendidikan_path(proyek_pendidikan) %></td>
        <td><%= link_to 'Destroy', proyek_pendidikan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyek Pendidikan', new_proyek_pendidikan_path %>

app/views/proyek_pendidikans/new.html.erb
<h1>New Proyek Pendidikan</h1>

<%= render 'form', proyek_pendidikan: @proyek_pendidikan %>

<%= link_to 'Back', proyek_pendidikans_path %>

app/views/proyek_pendidikans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kode pp:</strong>
  <%= @proyek_pendidikan.kode_pp %>
</p>

<p>
  <strong>Proyek pendidikan:</strong>
  <%= @proyek_pendidikan.proyek_pendidikan %>
</p>

<%= link_to 'Edit', edit_proyek_pendidikan_path(@proyek_pendidikan) %> |
<%= link_to 'Back', proyek_pendidikans_path %>