config/routes.rb
Rails.application.routes.draw do
  
  resources :mahasiswas
  resources :mata_kuliahs
  resources :proyek_pendidikans
  resources :program_studis
  resources :kelas
  resources :dosens
  get 'welcome/index'
  root to: 'homes#index'
  devise_for :users,
  
  controllers: { sessions: 'users/sessions' }   
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :homes
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dosen.rb
class Dosen < ApplicationRecord
end

app/models/kela.rb
class Kela < ApplicationRecord
end

app/models/mahasiswa.rb
class Mahasiswa < ApplicationRecord
end

app/models/mata_kuliah.rb
class MataKuliah < ApplicationRecord
end

app/models/program_studi.rb
class ProgramStudi < ApplicationRecord
end

app/models/proyek_pendidikan.rb
class ProyekPendidikan < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dosens_controller.rb
class DosensController < ApplicationController
  before_action :set_dosen, only: [:show, :edit, :update, :destroy]

  # GET /dosens
  # GET /dosens.json
  def index
    @dosens = Dosen.all
  end

  # GET /dosens/1
  # GET /dosens/1.json
  def show
  end

  # GET /dosens/new
  def new
    @dosen = Dosen.new
  end

  # GET /dosens/1/edit
  def edit
  end

  # POST /dosens
  # POST /dosens.json
  def create
    @dosen = Dosen.new(dosen_params)

    respond_to do |format|
      if @dosen.save
        format.html { redirect_to @dosen, notice: 'Dosen was successfully created.' }
        format.json { render :show, status: :created, location: @dosen }
      else
        format.html { render :new }
        format.json { render json: @dosen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dosens/1
  # PATCH/PUT /dosens/1.json
  def update
    respond_to do |format|
      if @dosen.update(dosen_params)
        format.html { redirect_to @dosen, notice: 'Dosen was successfully updated.' }
        format.json { render :show, status: :ok, location: @dosen }
      else
        format.html { render :edit }
        format.json { render json: @dosen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dosens/1
  # DELETE /dosens/1.json
  def destroy
    @dosen.destroy
    respond_to do |format|
      format.html { redirect_to dosens_url, notice: 'Dosen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dosen
      @dosen = Dosen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dosen_params
      params.require(:dosen).permit(:nik, :nama_dosen, :email)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :authenticate_user!
    def index
    end
end

app/controllers/kelas_controller.rb
class KelasController < ApplicationController
  before_action :set_kela, only: [:show, :edit, :update, :destroy]

  # GET /kelas
  # GET /kelas.json
  def index
    @kelas = Kela.all
  end

  # GET /kelas/1
  # GET /kelas/1.json
  def show
  end

  # GET /kelas/new
  def new
    @kela = Kela.new
  end

  # GET /kelas/1/edit
  def edit
  end

  # POST /kelas
  # POST /kelas.json
  def create
    @kela = Kela.new(kela_params)

    respond_to do |format|
      if @kela.save
        format.html { redirect_to @kela, notice: 'Kela was successfully created.' }
        format.json { render :show, status: :created, location: @kela }
      else
        format.html { render :new }
        format.json { render json: @kela.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kelas/1
  # PATCH/PUT /kelas/1.json
  def update
    respond_to do |format|
      if @kela.update(kela_params)
        format.html { redirect_to @kela, notice: 'Kela was successfully updated.' }
        format.json { render :show, status: :ok, location: @kela }
      else
        format.html { render :edit }
        format.json { render json: @kela.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kelas/1
  # DELETE /kelas/1.json
  def destroy
    @kela.destroy
    respond_to do |format|
      format.html { redirect_to kelas_url, notice: 'Kela was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kela
      @kela = Kela.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kela_params
      params.require(:kela).permit(:kode_kelas, :nama_kelas)
    end
end

app/controllers/mahasiswas_controller.rb
class MahasiswasController < ApplicationController
  before_action :set_mahasiswa, only: [:show, :edit, :update, :destroy]

  # GET /mahasiswas
  # GET /mahasiswas.json
  def index
    @mahasiswas = Mahasiswa.all
  end

  # GET /mahasiswas/1
  # GET /mahasiswas/1.json
  def show
  end

  # GET /mahasiswas/new
  def new
    @mahasiswa = Mahasiswa.new
  end

  # GET /mahasiswas/1/edit
  def edit
  end

  # POST /mahasiswas
  # POST /mahasiswas.json
  def create
    @mahasiswa = Mahasiswa.new(mahasiswa_params)

    respond_to do |format|
      if @mahasiswa.save
        format.html { redirect_to @mahasiswa, notice: 'Mahasiswa was successfully created.' }
        format.json { render :show, status: :created, location: @mahasiswa }
      else
        format.html { render :new }
        format.json { render json: @mahasiswa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mahasiswas/1
  # PATCH/PUT /mahasiswas/1.json
  def update
    respond_to do |format|
      if @mahasiswa.update(mahasiswa_params)
        format.html { redirect_to @mahasiswa, notice: 'Mahasiswa was successfully updated.' }
        format.json { render :show, status: :ok, location: @mahasiswa }
      else
        format.html { render :edit }
        format.json { render json: @mahasiswa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mahasiswas/1
  # DELETE /mahasiswas/1.json
  def destroy
    @mahasiswa.destroy
    respond_to do |format|
      format.html { redirect_to mahasiswas_url, notice: 'Mahasiswa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mahasiswa
      @mahasiswa = Mahasiswa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mahasiswa_params
      params.require(:mahasiswa).permit(:nrp, :nama, :tanggal_lahir, :tempat_lahir, :jenis_kelamin, :agama, :email, :no_hp, :alamat, :provinsi, :kota_kab, :kode_pos, :kecamatan, :desa_kelurahan, :no_ijazah, :tanggal_ijazah, :nem, :warga_negara, :gol_darah, :rhesus, :jalur_masuk, :status_mahasiswa, :nilai_toefl, :nama_lengkap_ayah, :tanggal_lahir_ayah, :tempat_lahir_ayah, :pekerjaan, :alamat_pekerjaan, :pendidikan_terakhir, :no_hp, :email_ayah, :nama_lengkap_ibu, :tanggal_lahir_ibu, :tempat_lahir_ibu, :pekerjaan_ibu, :alamat_pekerjaan_ibu, :pendidikan_terakhir_ibu, :no_hp_ibu, :email_ibu, :alamat_ortu, :provinsi_ortu, :kota_kab_ortu, :kode_pos_ortu, :kecamatan_ortu, :desa_kelurahan_ortu)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dosens_helper.rb
module DosensHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/kelas_helper.rb
module KelasHelper
end

app/helpers/mahasiswas_helper.rb
module MahasiswasHelper
end

app/helpers/mata_kuliahs_helper.rb
module MataKuliahsHelper
end

app/helpers/program_studis_helper.rb
module ProgramStudisHelper
end

app/helpers/proyek_pendidikans_helper.rb
module ProyekPendidikansHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dosens/_form.html.erb
<%= form_with(model: dosen, local: true) do |form| %>
  <% if dosen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dosen.errors.count, "error") %> prohibited this dosen from being saved:</h2>

      <ul>
      <% dosen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nik %>
    <%= form.text_field :nik %>
  </div>

  <div class="field">
    <%= form.label :nama_dosen %>
    <%= form.text_field :nama_dosen %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dosens/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
    <div class="card-body">
        <p class=content-header>Editing Dosen</p>
       <%= render 'form', dosen:@dosen %>
    </div>
</div>

app/views/dosens/index.html.erb
<style>
table {
  border: 1px solid black;
}
tr:hover {background-color: #f5f5f5;}
</style>


<p id="notice"><%= notice %></p>

<h1>Dosen</h1>


<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-9">
     
      </div>
      <div class="col-3 text-right">
        <%= link_to 'Data Baru',  new_dosen_path, class: "btn btn-sm btn-primary" %>
      </div>
    </div>
<div>
.
</div>

<table>
<table class="table table-striped">  
  <thead>
    <tr>
      <th>No</th>
      <th>Nik</th>
      <th>Nama dosen</th>
      <th>Email</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

   <tbody>
          <% @dosens.each_with_index do |dosen, index| %>
            <tr>
              <td><%= (index + 1) %> </td>
              <td><%= dosen.nik %></td>
              <td><%= dosen.nama_dosen %></td>
              <td><%= dosen.email %></td>
              <td><%= link_to 'Show', dosen %></td>
              <td><%= link_to 'Edit', edit_dosen_path(dosen) %></td>
              <td><%= link_to 'Destroy', dosen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </td>    
            </tr>
          <% end %>
  </tbody>
</table>

<br>

app/views/dosens/new.html.erb
<h1>New Dosen</h1>

<%= render 'form', dosen: @dosen %>

<%= link_to 'Back', dosens_path %>

app/views/dosens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nik:</strong>
  <%= @dosen.nik %>
</p>

<p>
  <strong>Nama dosen:</strong>
  <%= @dosen.nama_dosen %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dosen.email %>
</p>

<%= link_to 'Edit', edit_dosen_path(@dosen) %> |
<%= link_to 'Back', dosens_path %>

app/views/kelas/_form.html.erb
<%= form_with(model: kela, local: true) do |form| %>
  <% if kela.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kela.errors.count, "error") %> prohibited this kela from being saved:</h2>

      <ul>
      <% kela.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kode_kelas %>
    <%= form.text_field :kode_kelas %>
  </div>

  <div class="field">
    <%= form.label :nama_kelas %>
    <%= form.text_field :nama_kelas %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kelas/edit.html.erb
<h1>Editing Kela</h1>

<%= render 'form', kela: @kela %>

<%= link_to 'Show', @kela %> |
<%= link_to 'Back', kelas_path %>

app/views/kelas/index.html.erb
<style>
table {
  border: 1px solid black;
}
tr:hover {background-color: #f5f5f5;}
</style>


<p id="notice"><%= notice %></p>

<h1>Kelas</h1>


<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-9">
     
      </div>
      <div class="col-3 text-right">
        <%= link_to 'Data Baru',  new_kela_path, class: "btn btn-sm btn-primary" %>
      </div>
    </div>
<div>
.
</div>

<table>
<table class="table table-striped">  
  <thead>
    <tr>
      <th>No</th>
      <th>Kode Kelas</th>
      <th>Nama Kelas</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

   <tbody>
          <% @kelas.each_with_index do |kelas, index| %>
            <tr>
              <td><%= (index + 1) %> </td>
              <td><%= kelas.kode_kelas %></td>
              <td><%= kelas.nama_kelas %></td>
              <td><%= link_to 'Show', kelas %></td>
              <td><%= link_to 'Edit', edit_kela_path(kelas) %></td>
              <td><%= link_to 'Destroy', kelas, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </td>    
            </tr>
          <% end %>
  </tbody>
</table>

<br>

app/views/kelas/new.html.erb
<h1>New Kela</h1>

<%= render 'form', kela: @kela %>

<%= link_to 'Back', kelas_path %>

app/views/kelas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kode kelas:</strong>
  <%= @kela.kode_kelas %>
</p>

<p>
  <strong>Nama kelas:</strong>
  <%= @kela.nama_kelas %>
</p>

<%= link_to 'Edit', edit_kela_path(@kela) %> |
<%= link_to 'Back', kelas_path %>

app/views/mahasiswas/edit.html.erb
<h1>Editing Mahasiswa</h1>

<%= render 'form', mahasiswa: @mahasiswa %>

<%= link_to 'Show', @mahasiswa %> |
<%= link_to 'Back', mahasiswas_path %>

app/views/mahasiswas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mahasiswas</h1>

<table>
  <thead>
    <tr>
      <th>Nrp</th>
      <th>Nama</th>
      <th>Tanggal lahir</th>
      <th>Tempat lahir</th>
      <th>Jenis kelamin</th>
      <th>Agama</th>
      <th>Email</th>
      <th>No hp</th>
      <th>Alamat</th>
      <th>Provinsi</th>
      <th>Kota kab</th>
      <th>Kode pos</th>
      <th>Kecamatan</th>
      <th>Desa kelurahan</th>
      <th>No ijazah</th>
      <th>Tanggal ijazah</th>
      <th>Nem</th>
      <th>Warga negara</th>
      <th>Gol darah</th>
      <th>Rhesus</th>
      <th>Jalur masuk</th>
      <th>Status mahasiswa</th>
      <th>Nilai toefl</th>
      <th>Nama lengkap ayah</th>
      <th>Tanggal lahir ayah</th>
      <th>Tempat lahir ayah</th>
      <th>Pekerjaan</th>
      <th>Alamat pekerjaan</th>
      <th>Pendidikan terakhir</th>
      <th>No hp</th>
      <th>Email ayah</th>
      <th>Nama lengkap ibu</th>
      <th>Tanggal lahir ibu</th>
      <th>Tempat lahir ibu</th>
      <th>Pekerjaan ibu</th>
      <th>Alamat pekerjaan ibu</th>
      <th>Pendidikan terakhir ibu</th>
      <th>No hp ibu</th>
      <th>Email ibu</th>
      <th>Alamat ortu</th>
      <th>Provinsi ortu</th>
      <th>Kota kab ortu</th>
      <th>Kode pos ortu</th>
      <th>Kecamatan ortu</th>
      <th>Desa kelurahan ortu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mahasiswas.each do |mahasiswa| %>
      <tr>
        <td><%= mahasiswa.nrp %></td>
        <td><%= mahasiswa.nama %></td>
        <td><%= mahasiswa.tanggal_lahir %></td>
        <td><%= mahasiswa.tempat_lahir %></td>
        <td><%= mahasiswa.jenis_kelamin %></td>
        <td><%= mahasiswa.agama %></td>
        <td><%= mahasiswa.email %></td>
        <td><%= mahasiswa.no_hp %></td>
        <td><%= mahasiswa.alamat %></td>
        <td><%= mahasiswa.provinsi %></td>
        <td><%= mahasiswa.kota_kab %></td>
        <td><%= mahasiswa.kode_pos %></td>
        <td><%= mahasiswa.kecamatan %></td>
        <td><%= mahasiswa.desa_kelurahan %></td>
        <td><%= mahasiswa.no_ijazah %></td>
        <td><%= mahasiswa.tanggal_ijazah %></td>
        <td><%= mahasiswa.nem %></td>
        <td><%= mahasiswa.warga_negara %></td>
        <td><%= mahasiswa.gol_darah %></td>
        <td><%= mahasiswa.rhesus %></td>
        <td><%= mahasiswa.jalur_masuk %></td>
        <td><%= mahasiswa.status_mahasiswa %></td>
        <td><%= mahasiswa.nilai_toefl %></td>
        <td><%= mahasiswa.nama_lengkap_ayah %></td>
        <td><%= mahasiswa.tanggal_lahir_ayah %></td>
        <td><%= mahasiswa.tempat_lahir_ayah %></td>
        <td><%= mahasiswa.pekerjaan %></td>
        <td><%= mahasiswa.alamat_pekerjaan %></td>
        <td><%= mahasiswa.pendidikan_terakhir %></td>
        <td><%= mahasiswa.no_hp %></td>
        <td><%= mahasiswa.email_ayah %></td>
        <td><%= mahasiswa.nama_lengkap_ibu %></td>
        <td><%= mahasiswa.tanggal_lahir_ibu %></td>
        <td><%= mahasiswa.tempat_lahir_ibu %></td>
        <td><%= mahasiswa.pekerjaan_ibu %></td>
        <td><%= mahasiswa.alamat_pekerjaan_ibu %></td>
        <td><%= mahasiswa.pendidikan_terakhir_ibu %></td>
        <td><%= mahasiswa.no_hp_ibu %></td>
        <td><%= mahasiswa.email_ibu %></td>
        <td><%= mahasiswa.alamat_ortu %></td>
        <td><%= mahasiswa.provinsi_ortu %></td>
        <td><%= mahasiswa.kota_kab_ortu %></td>
        <td><%= mahasiswa.kode_pos_ortu %></td>
        <td><%= mahasiswa.kecamatan_ortu %></td>
        <td><%= mahasiswa.desa_kelurahan_ortu %></td>
        <td><%= link_to 'Show', mahasiswa %></td>
        <td><%= link_to 'Edit', edit_mahasiswa_path(mahasiswa) %></td>
        <td><%= link_to 'Destroy', mahasiswa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mahasiswa', new_mahasiswa_path %>

app/views/mahasiswas/new.html.erb
<h1>New Mahasiswa</h1>

<%= render 'form', mahasiswa: @mahasiswa %>

<%= link_to 'Back', mahasiswas_path %>

app/views/mahasiswas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nrp:</strong>
  <%= @mahasiswa.nrp %>
</p>

<p>
  <strong>Nama:</strong>
  <%= @mahasiswa.nama %>
</p>

<p>
  <strong>Tanggal lahir:</strong>
  <%= @mahasiswa.tanggal_lahir %>
</p>

<p>
  <strong>Tempat lahir:</strong>
  <%= @mahasiswa.tempat_lahir %>
</p>

<p>
  <strong>Jenis kelamin:</strong>
  <%= @mahasiswa.jenis_kelamin %>
</p>

<p>
  <strong>Agama:</strong>
  <%= @mahasiswa.agama %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mahasiswa.email %>
</p>

<p>
  <strong>No hp:</strong>
  <%= @mahasiswa.no_hp %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @mahasiswa.alamat %>
</p>

<p>
  <strong>Provinsi:</strong>
  <%= @mahasiswa.provinsi %>
</p>

<p>
  <strong>Kota kab:</strong>
  <%= @mahasiswa.kota_kab %>
</p>

<p>
  <strong>Kode pos:</strong>
  <%= @mahasiswa.kode_pos %>
</p>

<p>
  <strong>Kecamatan:</strong>
  <%= @mahasiswa.kecamatan %>
</p>

<p>
  <strong>Desa kelurahan:</strong>
  <%= @mahasiswa.desa_kelurahan %>
</p>

<p>
  <strong>No ijazah:</strong>
  <%= @mahasiswa.no_ijazah %>
</p>

<p>
  <strong>Tanggal ijazah:</strong>
  <%= @mahasiswa.tanggal_ijazah %>
</p>

<p>
  <strong>Nem:</strong>
  <%= @mahasiswa.nem %>
</p>

<p>
  <strong>Warga negara:</strong>
  <%= @mahasiswa.warga_negara %>
</p>

<p>
  <strong>Gol darah:</strong>
  <%= @mahasiswa.gol_darah %>
</p>

<p>
  <strong>Rhesus:</strong>
  <%= @mahasiswa.rhesus %>
</p>

<p>
  <strong>Jalur masuk:</strong>
  <%= @mahasiswa.jalur_masuk %>
</p>

<p>
  <strong>Status mahasiswa:</strong>
  <%= @mahasiswa.status_mahasiswa %>
</p>

<p>
  <strong>Nilai toefl:</strong>
  <%= @mahasiswa.nilai_toefl %>
</p>

<p>
  <strong>Nama lengkap ayah:</strong>
  <%= @mahasiswa.nama_lengkap_ayah %>
</p>

<p>
  <strong>Tanggal lahir ayah:</strong>
  <%= @mahasiswa.tanggal_lahir_ayah %>
</p>

<p>
  <strong>Tempat lahir ayah:</strong>
  <%= @mahasiswa.tempat_lahir_ayah %>
</p>

<p>
  <strong>Pekerjaan:</strong>
  <%= @mahasiswa.pekerjaan %>
</p>

<p>
  <strong>Alamat pekerjaan:</strong>
  <%= @mahasiswa.alamat_pekerjaan %>
</p>

<p>
  <strong>Pendidikan terakhir:</strong>
  <%= @mahasiswa.pendidikan_terakhir %>
</p>

<p>
  <strong>No hp:</strong>
  <%= @mahasiswa.no_hp %>
</p>

<p>
  <strong>Email ayah:</strong>
  <%= @mahasiswa.email_ayah %>
</p>

<p>
  <strong>Nama lengkap ibu:</strong>
  <%= @mahasiswa.nama_lengkap_ibu %>
</p>

<p>
  <strong>Tanggal lahir ibu:</strong>
  <%= @mahasiswa.tanggal_lahir_ibu %>
</p>

<p>
  <strong>Tempat lahir ibu:</strong>
  <%= @mahasiswa.tempat_lahir_ibu %>
</p>

<p>
  <strong>Pekerjaan ibu:</strong>
  <%= @mahasiswa.pekerjaan_ibu %>
</p>

<p>
  <strong>Alamat pekerjaan ibu:</strong>
  <%= @mahasiswa.alamat_pekerjaan_ibu %>
</p>

<p>
  <strong>Pendidikan terakhir ibu:</strong>
  <%= @mahasiswa.pendidikan_terakhir_ibu %>
</p>

<p>
  <strong>No hp ibu:</strong>
  <%= @mahasiswa.no_hp_ibu %>
</p>

<p>
  <strong>Email ibu:</strong>
  <%= @mahasiswa.email_ibu %>
</p>

<p>
  <strong>Alamat ortu:</strong>
  <%= @mahasiswa.alamat_ortu %>
</p>

<p>
  <strong>Provinsi ortu:</strong>
  <%= @mahasiswa.provinsi_ortu %>
</p>

<p>
  <strong>Kota kab ortu:</strong>
  <%= @mahasiswa.kota_kab_ortu %>
</p>

<p>
  <strong>Kode pos ortu:</strong>
  <%= @mahasiswa.kode_pos_ortu %>
</p>

<p>
  <strong>Kecamatan ortu:</strong>
  <%= @mahasiswa.kecamatan_ortu %>
</p>

<p>
  <strong>Desa kelurahan ortu:</strong>
  <%= @mahasiswa.desa_kelurahan_ortu %>
</p>

<%= link_to 'Edit', edit_mahasiswa_path(@mahasiswa) %> |
<%= link_to 'Back', mahasiswas_path %>